# Goal
std_msgs/String reason # reason why the server is called (unnecessary, but must action have a goal)
---
# Result
std_msgs/String status # ('success', 'failure', ..)
geometry_msgs/Pose robot_pose # robot's end pose
---
# Feedback
geometry_msgs/Pose robot_pose # robot's current pose
