# Goal
std_msgs/String human_pose_topic # topic with the human pose
std_msgs/Float64 distance # desired distance from human
---
# Result
std_msgs/String status # ('success', 'failure', ..)
geometry_msgs/Pose robot_pose # robot's end pose
---
# Feedback
geometry_msgs/Pose robot_pose # robot's current pose
